name = "aneko-photos"
main = "./dist/_worker.js"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat"]

[build]
command = "pnpm run build"

[assets]
directory = "./dist"

[[kv_namespaces]]
binding = "KV"
id = "e57524d3612149a7bd99349c2e7cb3ab"

[[r2_buckets]]
binding = "R2"
bucket_name = "photo"
